# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e3a6007f5af60c19a250cb024d63b545bf698f0041e7722ba1750ac68593366394d9802a73db5d62061fb70fd5ee74b4e6f9df986b074618ba463a0d054d82e

test:
  secret_key_base: 2ca9cef91a4cbe1199f8c4b8765f9421ac8ce09269b17a98bc7e627dcb3ad9dcb844f1554e14661fe2cd65efdbd130b1176722a1ae83467fdeaa2e6ea0de563e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
